type Lolly {
    id: ID!
    to: String!
    message: String!
    from: String!
    flavourTop: String!
    flavourMiddle: String!
    flavourBottom: String!
}

type Query{
    getLollyByID(id: ID!) : Lolly!
    getLollies: [Lolly!]
}

type Mutation{
    createLolly(to: String!, message: String!, from: String!, flavourTop: String!, flavourMiddle: String!, flavourBottom: String!): Lolly
}